MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [118.32, 86.955, 92.565]
  PIXEL_STD: [51.255, 47.175, 49.98]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  MASK_FORMER:
    TEST:
      OBJECT_MASK_THRESHOLD: 0.95
DATASETS:
  TRAIN_U: ("endovis2018_train_1_2_unlabeled",)
  TRAIN_L: ("endovis2018_train_1_2_labeled",)
  TEST: ("endovis2018_train",)
SOLVER:
  IMS_PER_BATCH: 20
  BASE_LR: 0.0001
  STEPS: (10186, 11035)
  MAX_ITER: 11460
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  MIN_SIZE_TRAIN: 256
  MAX_SIZE_TRAIN: 256
  MIN_SIZE_TEST: 256
  MAX_SIZE_TEST: 256
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "endovis2018_instance"
  #DATASET_MODE: "train_u"
TEST:
  #INSTANCE_ON: true
  #PANOPTIC_ON: false
  #SEMANTIC_ON: false
  EVAL_PERIOD: 100 #1500
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
SEED: 53073424
