_BASE_: Res50.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
  WEIGHTS: "https://dl.fbaipublicfiles.com/maskformer/mask2former/coco/panoptic/maskformer2_swin_tiny_bs16_50ep/model_final_9fd0ae.pkl"
  PIXEL_MEAN: [118.32, 86.955, 92.565]
  PIXEL_STD: [51.255, 47.175, 49.98]
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  #STEPS: (33956, 36785)
  #MAX_ITER: 38200

